# # name: CI

# on:
#   push:
#     branches:
#       - main

# name: Deploy Extension

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: npm install
#       - uses: lannonbr/vsce-action@4.0.0
#         with:
#           args: "publish -p $VSCE_TOKEN"
#         env:
#           VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
# name: CI

on:
  push:
    branches:
      - main

name: Deploy Extension

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.SEMVER_APPID }}
          private-key: ${{ secrets.SEMVER_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install --save-dev semantic-release semantic-release-vsce @semantic-release/changelog @semantic-release/git
      - name: Install deps
        run: npm ci
      - run: npx semantic-release
        env:
          # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          # In case you want to publish to Visual Studio Marketplace
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
